[package]
name = "f2i"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
fitsio = "0.21.7"
image = "0.25.5"
ndarray = "0.16.1"
ndarray-linalg = { version = "0.17.0", features = ["openblas-system"] }
viuer = "0.9.1"
